version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=luisf
      - MONGO_PASSWORD=mypassword
      - MONGO_DB=mydb
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: luisf
      MONGO_INITDB_ROOT_PASSWORD: mypassword
